// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/markopolo123/pico_templ/docs/templates"
	"github.com/markopolo123/pico_templ/layout/container"
)

func Layout() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1>Layout Components</h1><p class=\"lead\">Layout components help structure your page content. They provide consistent spacing, alignment, and responsive behavior using Pico CSS conventions.</p><nav><ul><li><a href=\"#container\">Container</a></li><li><a href=\"#grid\">Grid</a></li><li><a href=\"#group\">Group</a></li><li><a href=\"#tooltip\">Tooltip</a></li></ul></nav><hr><!-- Container Section --> <section id=\"container\"><h2>Container</h2><p>The Container component provides a centered, max-width wrapper for your content. Use it to constrain content width and add consistent horizontal padding. Choose between a standard container with a max-width or a fluid container that spans the full viewport width.</p><h3>Standard Container</h3><p>A centered container with a maximum width, ideal for readable content areas.</p><div style=\"background: var(--pico-muted-border-color); padding: 1rem; margin-bottom: 1rem;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div style=\"background: var(--pico-primary-background); color: var(--pico-primary-inverse); padding: 1rem; text-align: center;\">Standard Container Content</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = container.Container(container.Props{}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><pre><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(`@container.Container(container.Props{}) {
    <p>Your content here</p>
}`)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `docs/pages/layout.templ`, Line: 49, Col: 2}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</code></pre><h3>Fluid Container</h3><p>A full-width container that spans the entire viewport, useful for hero sections or full-bleed layouts.</p><div style=\"background: var(--pico-muted-border-color); padding: 1rem; margin-bottom: 1rem;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var5 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div style=\"background: var(--pico-secondary-background); color: var(--pico-secondary-inverse); padding: 1rem; text-align: center;\">Fluid Container Content (Full Width)</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = container.Container(container.Props{Fluid: true}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var5), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div><pre><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(`@container.Container(container.Props{Fluid: true}) {
    <p>Full-width content here</p>
}`)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `docs/pages/layout.templ`, Line: 65, Col: 2}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</code></pre><h3>Container with Custom Class</h3><p>Add custom CSS classes for additional styling.</p><pre><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(`@container.Container(container.Props{
    Class: "my-custom-class",
}) {
    <p>Content with custom styling</p>
}`)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `docs/pages/layout.templ`, Line: 76, Col: 2}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</code></pre><h3>Props Reference</h3><figure><table><thead><tr><th>Prop</th><th>Type</th><th>Default</th><th>Description</th></tr></thead> <tbody><tr><td><code>Fluid</code></td><td>bool</td><td>false</td><td>Use .container-fluid for full-width layout</td></tr><tr><td><code>Class</code></td><td>string</td><td>\"\"</td><td>Additional CSS classes to apply</td></tr><tr><td><code>Attrs</code></td><td>templ.Attributes</td><td>nil</td><td>Arbitrary additional HTML attributes</td></tr></tbody></table></figure></section><hr><!-- Grid Section (Coming Soon) --> <section id=\"grid\"><h2>Grid</h2><mark>Coming Soon</mark><p>The Grid component will provide a flexible CSS grid system for creating responsive multi-column layouts. It will support configurable columns, gaps, and alignment options.</p><h3>Planned Features</h3><ul><li>Configurable number of columns</li><li>Responsive breakpoints</li><li>Gap control (row and column)</li><li>Alignment options (items and content)</li></ul><h3>Preview (using native CSS grid)</h3><div style=\"display: grid; grid-template-columns: repeat(3, 1fr); gap: 1rem; margin-bottom: 1rem;\"><div style=\"background: var(--pico-primary-background); color: var(--pico-primary-inverse); padding: 1rem; text-align: center; border-radius: var(--pico-border-radius);\">Column 1</div><div style=\"background: var(--pico-primary-background); color: var(--pico-primary-inverse); padding: 1rem; text-align: center; border-radius: var(--pico-border-radius);\">Column 2</div><div style=\"background: var(--pico-primary-background); color: var(--pico-primary-inverse); padding: 1rem; text-align: center; border-radius: var(--pico-border-radius);\">Column 3</div></div><pre><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(`// Planned API (subject to change)
@grid.Grid(grid.Props{Columns: 3, Gap: "1rem"}) {
    <div>Column 1</div>
    <div>Column 2</div>
    <div>Column 3</div>
}`)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `docs/pages/layout.templ`, Line: 149, Col: 2}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</code></pre></section><hr><!-- Group Section (Coming Soon) --> <section id=\"group\"><h2>Group</h2><mark>Coming Soon</mark><p>The Group component will provide a flexbox-based horizontal or vertical grouping of elements with consistent spacing. Ideal for button groups, navigation items, or any collection of related elements.</p><h3>Planned Features</h3><ul><li>Horizontal and vertical orientation</li><li>Configurable gap spacing</li><li>Alignment and justification options</li><li>Wrap behavior control</li></ul><h3>Preview (using native flexbox)</h3><div style=\"display: flex; gap: 0.5rem; margin-bottom: 1rem;\"><button class=\"secondary\">Action 1</button> <button class=\"secondary\">Action 2</button> <button class=\"secondary\">Action 3</button></div><pre><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var9 string
			templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(`// Planned API (subject to change)
@group.Group(group.Props{Gap: "0.5rem"}) {
    <button>Action 1</button>
    <button>Action 2</button>
    <button>Action 3</button>
}`)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `docs/pages/layout.templ`, Line: 183, Col: 2}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</code></pre></section><hr><!-- Tooltip Section (Coming Soon) --> <section id=\"tooltip\"><h2>Tooltip</h2><mark>Coming Soon</mark><p>The Tooltip component will provide accessible tooltip functionality using Pico CSS's built-in tooltip support. Tooltips display additional information when users hover over or focus on an element.</p><h3>Planned Features</h3><ul><li>Multiple placement options (top, bottom, left, right)</li><li>Keyboard accessible</li><li>Custom tooltip content</li><li>Delay configuration</li></ul><h3>Preview (using native Pico tooltip)</h3><p>Hover over this <span data-tooltip=\"This is a tooltip!\" style=\"text-decoration: underline; cursor: help;\">underlined text</span> to see a tooltip.</p><pre><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var10 string
			templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(`// Planned API (subject to change)
@tooltip.Tooltip(tooltip.Props{
    Content: "This is a tooltip!",
    Position: "top",
}) {
    <span>Hover me</span>
}`)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `docs/pages/layout.templ`, Line: 216, Col: 2}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</code></pre></section><hr><!-- Usage Tips Section --> <section id=\"usage-tips\"><h2>Usage Tips</h2><h3>Import Statement</h3><pre><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var11 string
			templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(`import (
    "github.com/markopolo123/pico_templ/layout/container"
    // Future imports:
    // "github.com/markopolo123/pico_templ/layout/grid"
    // "github.com/markopolo123/pico_templ/layout/group"
    // "github.com/markopolo123/pico_templ/layout/tooltip"
)`)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `docs/pages/layout.templ`, Line: 233, Col: 2}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</code></pre><h3>Combining Layout Components</h3><p>Layout components can be nested and combined to create complex page structures. For example, use a Container to constrain width, then a Grid inside for multi-column content.</p><pre><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var12 string
			templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(`@container.Container(container.Props{}) {
    // Grid inside container
    <div class="grid">
        <div>Sidebar</div>
        <div>Main Content</div>
    </div>
}`)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `docs/pages/layout.templ`, Line: 250, Col: 2}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</code></pre></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = templates.Base(templates.BaseProps{
			Title:       "Layout",
			CurrentPath: "/layout",
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
